name: Percy
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * 1"
env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}
  PLATFORM_PROJECT_ID: ${{ secrets.PLATFORM_PROJECT_ID }}
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  WEBMASTER_GITHUB_ACTIONS_TOKEN: ${{ secrets.WEBMASTER_GITHUB_ACTIONS_TOKEN }}
  CYPRESS_ENV_JSON: ${{ secrets.CYPRESS_ENV_JSON }}
jobs:
  run_percy:
    runs-on: ubuntu-latest
    env: 
      PERCY_PARALLEL_TOTAL: 2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Psh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          ~/.platformsh/bin/platform project:set-remote ${{ secrets.PLATFORM_PROJECT_ID }}

      - name: Load certificate
        run: ~/.platformsh/bin/platform ssh-cert:load -y -vv

      - name: Add Psh to trusted keys
        continue-on-error: true
        run: |
          for ip in $(dig @8.8.8.8 git.us-2.platform.sh git.us.platform.sh git.us-4.platform.sh +short); do \
            ssh-keyscan git.us.platform.sh, git.us-2.platform.sh, git.us-4.platform.sh,$ip; \
            ssh-keyscan $ip; \
          done 2>/dev/null >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: ~/.platformsh/bin/platform redeploy -y
      - run: npm install
      - name: Set Up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Load Secrets from JSON to Env
        run: |
          echo '${{ secrets.CYPRESS_ENV_JSON }}' | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >> $GITHUB_ENV
      - run: npx percy exec -- node project/site_specific/tests/percy/percy.js && npx percy exec -- node project/global/tests/percy/percy.js